---
title: "POC Project 3"
author: "Angel Claudio"
date: "3/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(forcats)
```

```{r, message=F, warning=F}
mc_questions <- read_csv("./Data/multiple_choice_responses.csv")
questions_only <- read_csv("./Data/questions_only.csv")
txt_responses <- read_csv("./Data/other_text_responses.csv")

```

# FINDING FIRST FEATURE (COULD HAVE BEEN SKILLS, ETC.)

```{r exploring_titles}
#DATA MUNGING
mc_questions <- filter(mc_questions,!is.na(Q5) & !is.na(Q10)) %>% 
                filter(Q5 != "Other" & Q5 != "Student" & Q5 !="Not Employed") %>%
                filter(Q10 != "$0-999" & Q10 != "1,000-1,999"& Q10 != "2,000-2,999"
                       & Q10 != "3,000-3,999" & Q10 != "4,000-4,999" & Q10 != "5,000-7,499"
                       & Q10 != "7,500-9,999" & Q10 != "10,000-14,999" & Q10 != "15,000-19,999"
                       ) %>%
                .[-1,] 

#Frequency of Titles
ggplot(mc_questions, aes(fct_rev(fct_infreq(Q5)))) + 
                          geom_bar(aes(fill=Q5))  +
                          ylab("Job Titles") +
                          coord_flip() 


```

# POC TIE THINGS TO SALARY

```{r}
#SHOULD BE IN DATA MUNGING PART
salary_order <- c('20,000-24,999','25,000-29,999','30,000-39,999','40,000-49,999','50,000-59,999','60,000-69,999','70,000-79,999','80,000-89,999','90,000-99,999','100,000-124,999','125,000-149,999','150,000-199,999','200,000-249,999','250,000-299,999','300,000-500,000','> $500,000')

mc_questions$Q10 <- factor(mc_questions$Q10, levels=tolower(salary_order))

#TITLE RELATIONSHIP WITH SALARIES
ggplot(mc_questions) + geom_bar(aes(x=Q10, fill=Q5))  + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

